apiVersion: v1
kind: Service
metadata:
  name: rustdesk
  namespace: rustdesk
  labels:
    app: rustdesk
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - name: rustdesk-hbbs-nat-test
      port: 21115
      targetPort: 21115
      nodePort: 31115
    - name: rustdesk-hbbs-connect-udp
      port: 21116
      targetPort: 21116
      nodePort: 31116
      protocol: UDP
    - name: rustdesk-hbbs-connect-tcp
      port: 21116
      targetPort: 21116
      nodePort: 31116
    - name: rustdesk-hbbr-relay
      port: 21117
      targetPort: 21117
      nodePort: 31117
  selector:
    app: rustdesk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk
  namespace: rustdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk
  template:
    metadata:
      labels:
        app: rustdesk
        podName: rustdesk
    spec:
      restartPolicy: Always
      affinity:        # 配置节点反亲和
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: podName
                    operator: In
                    values:
                      - rustdesk
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10 #当删除Pod时，等待时间
      containers:
        - name: rustdesk-hbbs
          image: rustdesk/rustdesk-server:latest
          # hbbs -r <relay-server-ip[:port]>
          command: ["hbbs"]
          # 这里需要写入对外访问的域名
          args: ["-r","rust.home.domain.com:21117"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: client-data  #必须有名称
              mountPath: /root #机子内目录
            # 挂载一个空目录用于共享
#            - name: logs
#              # 容器内目录地址
#              mountPath: /app/logs
          resources:
            limits:
              memory: 1024Mi
          readinessProbe:              #就绪探针
            tcpSocket:
              port: 21118
            initialDelaySeconds: 20    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 10         #超时时间设置
            failureThreshold: 5        #探测失败的重试次数
          livenessProbe:               #存活探针
            tcpSocket:
              port: 21118
            initialDelaySeconds: 60    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 5          #超时时间设置
            failureThreshold: 3        #探测失败的重试次数
        - name: rustdesk-hbbr
          image: rustdesk/rustdesk-server:latest
          # hbbs -r <relay-server-ip[:port]>
          command: [ "hbbr" ]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: client-data  #必须有名称
              mountPath: /root #机子内目录
            # 挂载一个空目录用于共享
          #            - name: logs
          #              # 容器内目录地址
          #              mountPath: /app/logs
          resources:
            limits:
              memory: 1024Mi
          readinessProbe:              #就绪探针
            tcpSocket:
              port: 21119
            initialDelaySeconds: 20    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 10         #超时时间设置
            failureThreshold: 5        #探测失败的重试次数
          livenessProbe:               #存活探针
            tcpSocket:
              port: 21119
            initialDelaySeconds: 60    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 5          #超时时间设置
            failureThreshold: 3        #探测失败的重试次数
#        - name: filebeat
#          # 边车有版本要求，所以不加到这里来
#          #          lifecycle:
#          #            type: Sidecar
#          image: elastic/filebeat:7.9.3
#          imagePullPolicy: IfNotPresent
#          args:
#            - -environment
#            - container
#            - -c
#            - /app/config/filebeat.yml
#          volumeMounts:
#            # 独立的配置文件，这个配置文件通过kubectl create configmap --from-file=path
#            # kubectl create -n rustdesk configmap swagger2word-filebeat-config --from-file=`pwd`
#            # kubectl delete -n rustdesk configmap swagger2word-filebeat-config
#            - name: configs
#              # 机子内目录
#              mountPath: /app/config
#            - name: logs
#              #机子内目录
#              mountPath: /app/logs
#          resources:
#            limits:
#              memory: 200Mi
#          readinessProbe:
#            #使用命令检查
#            exec:
#              #指令，通过获取是否有锁来判断是否成功
#              command:
#                #指令
#                - cat
#                - /usr/share/filebeat/data/filebeat.lock
#            initialDelaySeconds: 20
#            periodSeconds: 5
#            timeoutSeconds: 10
#            failureThreshold: 5
#          livenessProbe:
#            exec:
#              command:
#                - cat
#                - /usr/share/filebeat/data/filebeat.lock
#            initialDelaySeconds: 20
#            periodSeconds: 5
#            timeoutSeconds: 5
#            failureThreshold: 3
      volumes:
        - name: client-data #挂载本机文件
          nfs:
            server: 192.168.3.15
            path: /data/nfs/data/rustdesk/data
#        - name: logs
#          emptyDir: {}
